### ISSUE TITLE
diff from the SSL app?

### ISSUE THREAD

**Issue by benoitc** [RoadRunnr/dtlsex#2]
Do you have a diff of the changes you made to make it happen? On which version is this based? I am wondering how much work it will require to be ported for Erlang 18.

**Comment by RoadRunnr** [comment]
@benoitc I thought that the README explained that?

DTLSex is the SSL application from R16B before the big TLS refactoring that went into R16B01. The history of the DTLS changes can be found at https://github.com/RoadRunnr/otp/tree/new_crypto_dtls, the remaining changes are just the renaming from SSL.

Since this is pre R16B01, porting it to R18 is a major task, but I guess you have already seen https://github.com/erlang/otp/pull/936 by now ;-)

I havn't test with R18, but there shouldn't be anything in R18 that prevents it from working. The erlang:now changes will certainly generate warnings, but those should be harmless.

**Comment by RoadRunnr** [comment]
the **ex** in the name stands for experimental. DTLs is now part of OTP and any project using this version needs to migrate to that.

Consider this project obsolete, abandoned and unsupported.
